### ISSUE TITLE
No real admin check

### ISSUE THREAD

**Issue by olafranzen** [henceee/1dv405-Webbramverk#8]
Dangerous/bad to check for admin rights by the user id

**Comment by henceee** [comment]
Well it says in the instructions we can hardcode it so............

**Comment by olafranzen** [comment]
Yeah maybe is so, I was thinking they meant the login credentials for the admin could be hardcoded, but I'm not sure really.

**Comment by 1dv450** [comment]
As @of222au said. The admin credentials could be hardcoded inte the DB (through rails c or seed.rb). The code in the application should not be hardcode
